export class PersonalInfoLabels {
    constructor(
        public title: any,
        public firstName: any,
        public middleName: any,
        public lastName: any,
        public fullName: any,
        public displayName: any,
        public employeeCode: any,
        public alternateEmployeeCode: any,
        public dateOfBirth: any,
        public gender: any,
        public bloodGroup: any,
        public nationality: any,
        public maritialStatus: any,
        public anniversaryDate: any,
        public isPhysicallyChallenged: any,
        public disabilityType: any,
        public severityLevel: any,
        public isExpatWorker: any,
        public countryOfOrigin: any,
        public isOnCOC: any,
        public cocValidTill: any,
        public cocNumber: any,
        public companyId: any,
        public employeeMasterId: any,
        public isActive: any,
    ){}

 }